# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Лимон333",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/6/
Content-Type: application/json

{
  "description": "23333Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/4/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=лимон2
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Склад 333",
  "positions": [
    {
      "product": 11,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 7,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/16/
Content-Type: application/json

{
  "positions": [
    {
      "product": 9,
      "quantity": 11111,
      "price": 1300.80
    },
    {
      "product": 7,
      "quantity": 243,
      "price": 14
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=7
Content-Type: application/json

###

# поиск складов, где есть определенный продукт по названию
GET {{baseUrl}}/stocks/?search=лимон333
Content-Type: application/json
